### ISSUE TITLE
Silent warns / note command

### ISSUE THREAD

**Issue by Purpzie** [AEnterprise/GearBot#193] opened 2019-04-03 22:17 UTC
(I posted this in the suggestions channel but I'll make it an issue too so it's easier to track.)

Basically the same as a warn but without DMing the user, and it wouldn't count as an infraction (like in `!userinfo`) but it would still show up in `!inf search`.

Most server mods can't simply set `!cfg dm_on_warn off` temporarily to do this, so this command would definitely help out.

**Comment by AEnterprise** [comment] 2019-04-04 06:53
duplicate of #86

**Closed by AEnterprise** 2019-04-04 06:53 UTC
